-- Listar todos Clientes que não tenham realizado uma compra.
SELECT CUS.*
FROM CUSTOMERS CUS
WHERE NOT EXISTS(SELECT 1 FROM ORDERS ORD WHERE ORD.CUSTOMER_ID=CUS.CUSTOMER_ID)
;

-- Listar os Produtos que não tenham sido comprados.
SELECT PRD.*
FROM PRODUCTS PRD
WHERE NOT EXISTS(SELECT 1 FROM ORDER_ITEMS ORD WHERE ORD.PRODUCT_ID=PRD.PRODUCT_ID)
;

-- Listar os Produtos sem Estoque.
SELECT 
  PRD.PRODUCT_NAME
FROM
  PRODUCTS PRD
  LEFT JOIN STOCKS STO ON STO.PRODUCT_ID=PRD.PRODUCT_ID
HAVING SUM(NVL(STO.QUANTITY, 0)) = 0
GROUP BY PRD.PRODUCT_NAME
;

-- Agrupar a quantidade de vendas que uma determinada Marca por Loja.
SELECT
   STO.STORE_NAME,
   COUNT(DISTINCT ORDER_ID) AS TOTAL_VENDAS
FROM
  ORDERS ORD
  INNER JOIN STORES STO      ON STO.STORE_ID=ORD.STORE_ID
  INNER JOIN ORDER_ITEMS ITM ON ITM.ORDER_ID=ORD.ORDER_ID
  INNER JOIN PRODUCTS PRD    ON PRD.PRODUCT_ID=ORD.PRODUCT_ID
  INNER JOIN BRANDS BRD      ON BRD.BRAND_ID=PRD.BRAND_ID
WHERE
  BRD.BRAND_NAME = 'Marca'
GROUP BY STO.STORE_NAME
;

-- Listar os Funcionarios que não estejam relacionados a um Pedido.
SELECT STF.*
FROM STAFFS STF
WHERE NOT EXISTS(SELECT 1 FROM ORDERS ORD WHERE ORD.STAFF_ID=STF.STAFF_ID)
;

